/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 mannequin3.glb
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/mannequin3.glb")
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig1Hips} />
          <skinnedMesh
            name="Ch36"
            geometry={nodes.Ch36.geometry}
            material={materials.Ch36_Body}
            skeleton={nodes.Ch36.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/mannequin3.glb")
